In [1]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\vanes\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\vanes\anaconda3\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\vanes\anaconda3\lib\site-packages (from ucimlrepo) (2024.8.30)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vanes\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vanes\appdata\roaming\python\python312\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vanes\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vanes\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\vanes\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [3]:
# import csv
# bike_sharing = pd.read_csv(r'

### Bring in Capital Bike Share DataSet

In [4]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
bike_sharing = fetch_ucirepo(id=275) 
  
# data (as pandas dataframes) 
X = bike_sharing.data.features 
y = bike_sharing.data.targets 
  
# metadata 
print(bike_sharing.metadata) 
  
# variable information 
print(bike_sharing.variables)

{'uci_id': 275, 'name': 'Bike Sharing', 'repository_url': 'https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset', 'data_url': 'https://archive.ics.uci.edu/static/public/275/data.csv', 'abstract': 'This dataset contains the hourly and daily count of rental bikes between years 2011 and 2012 in Capital bikeshare system with the corresponding weather and seasonal information.', 'area': 'Social Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 17389, 'num_features': 13, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['cnt'], 'index_col': ['instant'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2013, 'last_updated': 'Sun Mar 10 2024', 'dataset_doi': '10.24432/C5W894', 'creators': ['Hadi Fanaee-T'], 'intro_paper': {'ID': 422, 'type': 'NATIVE', 'title': 'Event labeling combining ensemble detectors and background knowledge', 'authors': 'Hadi Fanaee-T, Jo√£o Gama', 'venue': 'Progress in Artificial Intelligence', 'year': 2013, 'journal': None, 'DOI': '10.1007/s13748-013-0040-3', 'URL': 'https://www.semanticscholar.org/paper/bc42899f599d31a5d759f3e0a3ea8b52479d6423', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues. \r\n\r\nApart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv\r\n\t\r\n\t- instant: record index\r\n\t- dteday : date\r\n\t- season : season (1:winter, 2:spring, 3:summer, 4:fall)\r\n\t- yr : year (0: 2011, 1:2012)\r\n\t- mnth : month ( 1 to 12)\r\n\t- hr : hour (0 to 23)\r\n\t- holiday : weather day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)\r\n\t- weekday : day of the week\r\n\t- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.\r\n\t+ weathersit : \r\n\t\t- 1: Clear, Few clouds, Partly cloudy, Partly cloudy\r\n\t\t- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist\r\n\t\t- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds\r\n\t\t- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog\r\n\t- temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)\r\n\t- atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)\r\n\t- hum: Normalized humidity. The values are divided to 100 (max)\r\n\t- windspeed: Normalized wind speed. The values are divided to 67 (max)\r\n\t- casual: count of casual users\r\n\t- registered: count of registered users\r\n\t- cnt: count of total rental bikes including both casual and registered\r\n', 'citation': None}}
          name     role         type demographic  \
0      instant       ID      Integer        None
1       dteday  Feature         Date        None
2       season  Feature  Categorical        None
3           yr  Feature  Categorical        None
4         mnth  Feature  Categorical        None
5           hr  Feature  Categorical        None
6      holiday  Feature       Binary        None
7      weekday  Feature  Categorical        None
8   workingday  Feature       Binary        None
9   weathersit  Feature  Categorical        None
10        temp  Feature   Continuous        None
11       atemp  Feature   Continuous        None
12         hum  Feature   Continuous        None
13   windspeed  Feature   Continuous        None
14      casual    Other      Integer        None
15  registered    Other      Integer        None
16         cnt   Target      Integer        None

                                          description units missing_values
0                                        record index  None             no
1                                                date  None             no
2                1:winter, 2:spring, 3:summer, 4:fall  None             no
3                             year (0: 2011, 1: 2012)  None             no
4                                     month (1 to 12)  None             no
5                                      hour (0 to 23)  None             no
6   weather day is holiday or not (extracted from ...  None             no
7                                     day of the week  None             no
8   if day is neither weekend nor holiday is 1, ot...  None             no
9   - 1: Clear, Few clouds, Partly cloudy, Partly ...  None             no
10  Normalized temperature in Celsius. The values ...     C             no
11  Normalized feeling temperature in Celsius. The...     C             no
12  Normalized humidity. The values are divided to...  None             no
13  Normalized wind speed. The values are divided ...  None             no
14                              count of casual users  None             no
15                          count of registered users  None             no
16  count of total rental bikes including both cas...  None             no

In [5]:
X.head()

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed
0,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0
1,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0
2,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0
3,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0
4,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0

In [6]:
y.head()

   cnt
0   16
1   40
2   32
3   13
4    1

In [7]:
print(X)

           dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0      2011-01-01       1   0     1   0        0        6           0
1      2011-01-01       1   0     1   1        0        6           0
2      2011-01-01       1   0     1   2        0        6           0
3      2011-01-01       1   0     1   3        0        6           0
4      2011-01-01       1   0     1   4        0        6           0
...           ...     ...  ..   ...  ..      ...      ...         ...
17374  2012-12-31       1   1    12  19        0        1           1
17375  2012-12-31       1   1    12  20        0        1           1
17376  2012-12-31       1   1    12  21        0        1           1
17377  2012-12-31       1   1    12  22        0        1           1
17378  2012-12-31       1   1    12  23        0        1           1

       weathersit  temp   atemp   hum  windspeed
0               1  0.24  0.2879  0.81     0.0000
1               1  0.22  0.2727  0.80     0.0000
2               1  0.22  0.2727  0.80     0.0000
3               1  0.24  0.2879  0.75     0.0000
4               1  0.24  0.2879  0.75     0.0000
...           ...   ...     ...   ...        ...
17374           2  0.26  0.2576  0.60     0.1642
17375           2  0.26  0.2576  0.60     0.1642
17376           1  0.26  0.2576  0.60     0.1642
17377           1  0.26  0.2727  0.56     0.1343
17378           1  0.26  0.2727  0.65     0.1343

[17379 rows x 13 columns]

In [8]:
print(bike_sharing)

{'data': {'ids':        instant
0            1
1            2
2            3
3            4
4            5
...        ...
17374    17375
17375    17376
17376    17377
17377    17378
17378    17379

[17379 rows x 1 columns], 'features':            dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0      2011-01-01       1   0     1   0        0        6           0
1      2011-01-01       1   0     1   1        0        6           0
2      2011-01-01       1   0     1   2        0        6           0
3      2011-01-01       1   0     1   3        0        6           0
4      2011-01-01       1   0     1   4        0        6           0
...           ...     ...  ..   ...  ..      ...      ...         ...
17374  2012-12-31       1   1    12  19        0        1           1
17375  2012-12-31       1   1    12  20        0        1           1
17376  2012-12-31       1   1    12  21        0        1           1
17377  2012-12-31       1   1    12  22        0        1           1
17378  2012-12-31       1   1    12  23        0        1           1

       weathersit  temp   atemp   hum  windspeed
0               1  0.24  0.2879  0.81     0.0000
1               1  0.22  0.2727  0.80     0.0000
2               1  0.22  0.2727  0.80     0.0000
3               1  0.24  0.2879  0.75     0.0000
4               1  0.24  0.2879  0.75     0.0000
...           ...   ...     ...   ...        ...
17374           2  0.26  0.2576  0.60     0.1642
17375           2  0.26  0.2576  0.60     0.1642
17376           1  0.26  0.2576  0.60     0.1642
17377           1  0.26  0.2727  0.56     0.1343
17378           1  0.26  0.2727  0.65     0.1343

[17379 rows x 13 columns], 'targets':        cnt
0       16
1       40
2       32
3       13
4        1
...    ...
17374  119
17375   89
17376   90
17377   61
17378   49

[17379 rows x 1 columns], 'original':        instant      dteday  season  yr  mnth  hr  holiday  weekday  \
0            1  2011-01-01       1   0     1   0        0        6
1            2  2011-01-01       1   0     1   1        0        6
2            3  2011-01-01       1   0     1   2        0        6
3            4  2011-01-01       1   0     1   3        0        6
4            5  2011-01-01       1   0     1   4        0        6
...        ...         ...     ...  ..   ...  ..      ...      ...
17374    17375  2012-12-31       1   1    12  19        0        1
17375    17376  2012-12-31       1   1    12  20        0        1
17376    17377  2012-12-31       1   1    12  21        0        1
17377    17378  2012-12-31       1   1    12  22        0        1
17378    17379  2012-12-31       1   1    12  23        0        1

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
0               0           1  0.24  0.2879  0.81     0.0000       3
1               0           1  0.22  0.2727  0.80     0.0000       8
2               0           1  0.22  0.2727  0.80     0.0000       5
3               0           1  0.24  0.2879  0.75     0.0000       3
4               0           1  0.24  0.2879  0.75     0.0000       0
...           ...         ...   ...     ...   ...        ...     ...
17374           1           2  0.26  0.2576  0.60     0.1642      11
17375           1           2  0.26  0.2576  0.60     0.1642       8
17376           1           1  0.26  0.2576  0.60     0.1642       7
17377           1           1  0.26  0.2727  0.56     0.1343      13
17378           1           1  0.26  0.2727  0.65     0.1343      12

       registered  cnt
0              13   16
1              32   40
2              27   32
3              10   13
4               1    1
...           ...  ...
17374         108  119
17375          81   89
17376          83   90
17377          48   61
17378          37   49

[17379 rows x 17 columns], 'headers': Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')}, 'metadata': {'uci_id': 275, 'name': 'Bike Sharing', 'repository_url': 'https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset', 'data_url': 'https://archive.ics.uci.edu/static/public/275/data.csv', 'abstract': 'This dataset contains the hourly and daily count of rental bikes between years 2011 and 2012 in Capital bikeshare system with the corresponding weather and seasonal information.', 'area': 'Social Science', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 17389, 'num_features': 13, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['cnt'], 'index_col': ['instant'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2013, 'last_updated': 'Sun Mar 10 2024', 'dataset_doi': '10.24432/C5W894', 'creators': ['Hadi Fanaee-T'], 'intro_paper': {'ID': 422, 'type': 'NATIVE', 'title': 'Event labeling combining ensemble detectors and background knowledge', 'authors': 'Hadi Fanaee-T, Jo√£o Gama', 'venue': 'Progress in Artificial Intelligence', 'year': 2013, 'journal': None, 'DOI': '10.1007/s13748-013-0040-3', 'URL': 'https://www.semanticscholar.org/paper/bc42899f599d31a5d759f3e0a3ea8b52479d6423', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, environmental and health issues. \r\n\r\nApart from interesting real world applications of bike sharing systems, the characteristics of data being generated by these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important events in the city could be detected via monitoring these data.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Both hour.csv and day.csv have the following fields, except hr which is not available in day.csv\r\n\t\r\n\t- instant: record index\r\n\t- dteday : date\r\n\t- season : season (1:winter, 2:spring, 3:summer, 4:fall)\r\n\t- yr : year (0: 2011, 1:2012)\r\n\t- mnth : month ( 1 to 12)\r\n\t- hr : hour (0 to 23)\r\n\t- holiday : weather day is holiday or not (extracted from http://dchr.dc.gov/page/holiday-schedule)\r\n\t- weekday : day of the week\r\n\t- workingday : if day is neither weekend nor holiday is 1, otherwise is 0.\r\n\t+ weathersit : \r\n\t\t- 1: Clear, Few clouds, Partly cloudy, Partly cloudy\r\n\t\t- 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds, Mist\r\n\t\t- 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds, Light Rain + Scattered clouds\r\n\t\t- 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog\r\n\t- temp : Normalized temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-8, t_max=+39 (only in hourly scale)\r\n\t- atemp: Normalized feeling temperature in Celsius. The values are derived via (t-t_min)/(t_max-t_min), t_min=-16, t_max=+50 (only in hourly scale)\r\n\t- hum: Normalized humidity. The values are divided to 100 (max)\r\n\t- windspeed: Normalized wind speed. The values are divided to 67 (max)\r\n\t- casual: count of casual users\r\n\t- registered: count of registered users\r\n\t- cnt: count of total rental bikes including both casual and registered\r\n', 'citation': None}}, 'variables':           name     role         type demographic  \
0      instant       ID      Integer        None
1       dteday  Feature         Date        None
2       season  Feature  Categorical        None
3           yr  Feature  Categorical        None
4         mnth  Feature  Categorical        None
5           hr  Feature  Categorical        None
6      holiday  Feature       Binary        None
7      weekday  Feature  Categorical        None
8   workingday  Feature       Binary        None
9   weathersit  Feature  Categorical        None
10        temp  Feature   Continuous        None
11       atemp  Feature   Continuous        None
12         hum  Feature   Continuous        None
13   windspeed  Feature   Continuous        None
14      casual    Other      Integer        None
15  registered    Other      Integer        None
16         cnt   Target      Integer        None

                                          description units missing_values
0                                        record index  None             no
1                                                date  None             no
2                1:winter, 2:spring, 3:summer, 4:fall  None             no
3                             year (0: 2011, 1: 2012)  None             no
4                                     month (1 to 12)  None             no
5                                      hour (0 to 23)  None             no
6   weather day is holiday or not (extracted from ...  None             no
7                                     day of the week  None             no
8   if day is neither weekend nor holiday is 1, ot...  None             no
9   - 1: Clear, Few clouds, Partly cloudy, Partly ...  None             no
10  Normalized temperature in Celsius. The values ...     C             no
11  Normalized feeling temperature in Celsius. The...     C             no
12  Normalized humidity. The values are divided to...  None             no
13  Normalized wind speed. The values are divided ...  None             no
14                              count of casual users  None             no
15                          count of registered users  None             no
16  count of total rental bikes including both cas...  None             no  }

In [9]:
bike_sharing_concat = pd.concat([X,y],axis=1)

In [10]:
bike_sharing_concat

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,cnt
0,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,16
1,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,40
2,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,32
3,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,13
4,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,119
17375,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,89
17376,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,90
17377,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,61
17378,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,49